proposed network diagram
devsecfranklin/pso-ssg-631528 pull request #22
Opened 2021-08-30 11:40 UTC by devsecfranklin

- updated network diagram

2021-08-31 08:30 UTC, damianfedeczko commented
Looking at the diagram, I see 2 pairs of VM-Series, I though they want 3 pairs - one for inbound, one for inbound and east-west and one for Global Protect?

2021-08-31 08:31 UTC, damianfedeczko requested changes
Please lt me know about the number of VM pairs in the comment section - then I can approve the changes.

2021-08-31 09:30 UTC, devsecfranklin commented
> Please lt me know about the number of VM pairs in the comment section - then I can approve the changes.

yes it has been changing back and forth. I think we have the final answer. 

```
<div class="aju"><div class="aCi"><img id=":mw_31-e" name=":mw" src="https://lh3.googleusercontent.com/a-/AOh14GiMf0u-nK5NXbHV7rmHrLVBrFic7pb0Usgg9OiD=s40" class="ajn" jid="cdevchand@paloaltonetworks.com" data-hovercard-id="cdevchand@paloaltonetworks.com" data-name="Chet Devchand" aria-hidden="true"></div></div><div class="gs"><div class="gE iv gt">

Chet Devchand | Chet Devchand | Mon, Aug 30, 11:20 PM (6 hours ago)
-- | -- | --
Chet Devchand

```

2021-09-01 11:13 UTC, damianfedeczko approved these changes

2021-09-01 14:09 UTC, merged